export const ROOM_LAYOUT = [
  { id: 'cafeteria', center: [-11, 0, 33], size: [14, 4, 14], theme: 'cafeteria', connections: ['weapons', 'admin', 'storage', 'medbay', 'upperEngine'] },
  { id: 'weapons', center: [11, 0, 11], size: [8, 4, 8], theme: 'weapons', connections: ['cafeteria', 'navigation', 'o2', 'shields'] },
  { id: 'navigation', center: [33, 0, 33], size: [8, 4, 8], theme: 'controls', connections: ['weapons', 'o2', 'shields'] },
  { id: 'o2', center: [33, 0, 11], size: [6, 4, 6], theme: 'greenhouse', connections: ['weapons', 'navigation', 'shields'] },
  { id: 'shields', center: [33, 0, -11], size: [8, 4, 8], theme: 'controls', connections: ['navigation', 'o2', 'weapons', 'communications', 'storage'] },
  { id: 'communications', center: [33, 0, -33], size: [8, 4, 6], theme: 'servers', connections: ['shields', 'storage'] },
  { id: 'storage', center: [11, 0, -33], size: [10, 4, 10], theme: 'storage', connections: ['cafeteria', 'communications', 'shields', 'electrical', 'lowerEngine'] },
  { id: 'electrical', center: [-11, 0, -11], size: [8, 4, 8], theme: 'electrical', connections: ['storage', 'lowerEngine', 'admin'] },
  { id: 'lowerEngine', center: [-33, 0, -11], size: [8, 4, 8], theme: 'engine', connections: ['electrical', 'storage', 'security', 'reactor'] },
  { id: 'upperEngine', center: [-33, 0, 11], size: [8, 4, 8], theme: 'engine', connections: ['cafeteria', 'security', 'reactor'] },
  { id: 'security', center: [-11, 0, -33], size: [6, 4, 6], theme: 'security', connections: ['upperEngine', 'lowerEngine', 'reactor'] },
  { id: 'reactor', center: [-33, 0, -33], size: [8, 4, 10], theme: 'reactor', connections: ['upperEngine', 'lowerEngine', 'security'] },
  { id: 'medbay', center: [-11, 0, 11], size: [8, 4, 8], theme: 'medbay', connections: ['cafeteria', 'admin'] },
  { id: 'admin', center: [11, 0, -11], size: [8, 4, 8], theme: 'admin', connections: ['cafeteria', 'medbay', 'electrical'] },
]
